package test

// Code generated by jsonapi. DO NOT EDIT.
// Source: github.com/pentops/o5-test-app/internal/genclient/test/v1/test

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	url "net/url"

	list "github.com/pentops/o5-test-app/internal/genclient/psm/list/v1/list"
	state "github.com/pentops/o5-test-app/internal/genclient/psm/state/v1/state"
)

type Requester interface {
	Request(ctx context.Context, method string, path string, body interface{}, response interface{}) error
}

// GreetingQueryService
type GreetingQueryService struct {
	Requester
}

func NewGreetingQueryService(requester Requester) *GreetingQueryService {
	return &GreetingQueryService{
		Requester: requester,
	}
}

func (s GreetingQueryService) GetGreeting(ctx context.Context, req *GetGreetingRequest) (*GetGreetingResponse, error) {
	path := fmt.Sprintf("/test/v1/q/greeting/%s",
		req.GreetingId,
	)
	resp := &GetGreetingResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s GreetingQueryService) ListGreetings(ctx context.Context, req *ListGreetingsRequest) (*ListGreetingsResponse, error) {
	path := fmt.Sprintf("/test/v1/q/greeting")
	resp := &ListGreetingsResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s GreetingQueryService) ListGreetingEvents(ctx context.Context, req *ListGreetingEventsRequest) (*ListGreetingEventsResponse, error) {
	path := fmt.Sprintf("/test/v1/q/greeting/%s/events",
		req.GreetingId,
	)
	resp := &ListGreetingEventsResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// GreetingCommandService
type GreetingCommandService struct {
	Requester
}

func NewGreetingCommandService(requester Requester) *GreetingCommandService {
	return &GreetingCommandService{
		Requester: requester,
	}
}

func (s GreetingCommandService) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	path := fmt.Sprintf("/test/v1/echo")
	resp := &HelloResponse{}
	err := s.Request(ctx, "POST", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// GreetingEventType_Initiated Proto: test.v1.GreetingEventType.Initiated
type GreetingEventType_Initiated struct {
	Name        string     `json:"name,omitempty"`
	AppVersion  string     `json:"appVersion,omitempty"`
	WorkerError *TestError `json:"workerError,omitempty"`
}

// HelloRequest
type HelloRequest struct {
	GreetingId  string     `json:"greetingId,omitempty"`
	Name        string     `json:"name"`
	ThrowError  *TestError `json:"throwError,omitempty"`
	WorkerError *TestError `json:"workerError,omitempty"`
}

// HelloResponse
type HelloResponse struct {
	Greeting *GreetingState `json:"greeting,omitempty"`
}

// GetGreetingRequest
type GetGreetingRequest struct {
	GreetingId string `json:"-" path:"greetingId"`
}

// GreetingState Proto: test.v1.GreetingState
type GreetingState struct {
	Metadata   *state.StateMetadata `json:"metadata"`
	GreetingId string               `json:"greetingId,omitempty"`
	Status     string               `json:"status,omitempty"`
	Data       *GreetingStateData   `json:"data,omitempty"`
}

// ListGreetingsResponse
type ListGreetingsResponse struct {
	Greetings []*GreetingState   `json:"greetings,omitempty"`
	Page      *list.PageResponse `json:"page,omitempty"`
}

func (s ListGreetingsResponse) GetPageToken() *string {
	if s.Page == nil {
		return nil
	}
	return s.Page.NextToken
}

func (s ListGreetingsResponse) GetItems() []*GreetingState {
	return s.Greetings
}

// GreetingEventType Proto: test.v1.GreetingEventType
type GreetingEventType struct {
	Type *GreetingEventType_type `json:"type,omitempty"`
}

// GreetingEventType_Replied Proto: test.v1.GreetingEventType.Replied
type GreetingEventType_Replied struct {
	ReplyMessage string `json:"replyMessage,omitempty"`
}

// GetGreetingResponse
type GetGreetingResponse struct {
	Greeting *GreetingState `json:"greeting,omitempty"`
}

// GreetingEvent Proto: test.v1.GreetingEvent
type GreetingEvent struct {
	Metadata   *state.EventMetadata `json:"metadata"`
	GreetingId string               `json:"greetingId,omitempty"`
	Event      *GreetingEventType   `json:"event"`
}

// ListGreetingEventsRequest
type ListGreetingEventsRequest struct {
	GreetingId string             `json:"-" path:"greetingId"`
	Page       *list.PageRequest  `json:"-" query:"page"`
	Query      *list.QueryRequest `json:"-" query:"query"`
}

func (s ListGreetingEventsRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	if s.Page != nil {
		bb, err := json.Marshal(s.Page)
		if err != nil {
			return nil, err
		}
		values.Set("page", string(bb))
	}
	if s.Query != nil {
		bb, err := json.Marshal(s.Query)
		if err != nil {
			return nil, err
		}
		values.Set("query", string(bb))
	}
	return values, nil
}

func (s *ListGreetingEventsRequest) SetPageToken(pageToken string) {
	if s.Page == nil {
		s.Page = &list.PageRequest{}
	}
	s.Page.Token = &pageToken
}

// ListGreetingsRequest
type ListGreetingsRequest struct {
	Page  *list.PageRequest  `json:"-" query:"page"`
	Query *list.QueryRequest `json:"-" query:"query"`
}

func (s ListGreetingsRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	if s.Page != nil {
		bb, err := json.Marshal(s.Page)
		if err != nil {
			return nil, err
		}
		values.Set("page", string(bb))
	}
	if s.Query != nil {
		bb, err := json.Marshal(s.Query)
		if err != nil {
			return nil, err
		}
		values.Set("query", string(bb))
	}
	return values, nil
}

func (s *ListGreetingsRequest) SetPageToken(pageToken string) {
	if s.Page == nil {
		s.Page = &list.PageRequest{}
	}
	s.Page.Token = &pageToken
}

// ListGreetingEventsResponse
type ListGreetingEventsResponse struct {
	Events []*GreetingEvent   `json:"events,omitempty"`
	Page   *list.PageResponse `json:"page,omitempty"`
}

func (s ListGreetingEventsResponse) GetPageToken() *string {
	if s.Page == nil {
		return nil
	}
	return s.Page.NextToken
}

func (s ListGreetingEventsResponse) GetItems() []*GreetingEvent {
	return s.Events
}

// GreetingEventType_type Proto: test.v1.GreetingEventType.type
type GreetingEventType_type struct {
	Initiated *GreetingEventType_Initiated `json:"initiated,omitempty"`
	Replied   *GreetingEventType_Replied   `json:"replied,omitempty"`
}

func (s GreetingEventType_type) OneofKey() string {
	if s.Initiated != nil {
		return "initiated"
	}
	if s.Replied != nil {
		return "replied"
	}
	return ""
}

func (s GreetingEventType_type) Type() interface{} {
	if s.Initiated != nil {
		return s.Initiated
	}
	if s.Replied != nil {
		return s.Replied
	}
	return nil
}

// TestError Proto: test.v1.TestError
type TestError struct {
	Message string `json:"message,omitempty"`
	Code    int64  `json:"code,omitempty"`
}

// GreetingStateData Proto: test.v1.GreetingStateData
type GreetingStateData struct {
	Name         string  `json:"name,omitempty"`
	ReplyMessage *string `json:"replyMessage,omitempty"`
	AppVersion   string  `json:"appVersion,omitempty"`
}
