package test

// Code generated by jsonapi. DO NOT EDIT.
// Source: github.com/pentops/o5-test-app/internal/genclient/test/v1/test

import (
	context "context"
	json "encoding/json"
	errors "errors"
	list "github.com/pentops/o5-test-app/internal/genclient/j5/list/v1/list"
	state "github.com/pentops/o5-test-app/internal/genclient/j5/state/v1/state"
	url "net/url"
	strings "strings"
)

type Requester interface {
	Request(ctx context.Context, method string, path string, body interface{}, response interface{}) error
}

// GreetingCommandService
type GreetingCommandService struct {
	Requester
}

func NewGreetingCommandService(requester Requester) *GreetingCommandService {
	return &GreetingCommandService{
		Requester: requester,
	}
}

func (s GreetingCommandService) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	pathParts := make([]string, 4)
	pathParts[0] = ""
	pathParts[1] = "test"
	pathParts[2] = "v1"
	pathParts[3] = "echo"
	path := strings.Join(pathParts, "/")
	resp := &HelloResponse{}
	err := s.Request(ctx, "POST", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// HelloRequest
type HelloRequest struct {
	GreetingId  string     `json:"greetingId,omitempty"`
	Name        string     `json:"name"`
	ThrowError  *TestError `json:"throwError,omitempty"`
	WorkerError *TestError `json:"workerError,omitempty"`
}

// HelloResponse
type HelloResponse struct {
	Greeting *GreetingState `json:"greeting,omitempty"`
}

// GreetingQueryService
type GreetingQueryService struct {
	Requester
}

func NewGreetingQueryService(requester Requester) *GreetingQueryService {
	return &GreetingQueryService{
		Requester: requester,
	}
}

func (s GreetingQueryService) GetGreeting(ctx context.Context, req *GetGreetingRequest) (*GetGreetingResponse, error) {
	pathParts := make([]string, 6)
	pathParts[0] = ""
	pathParts[1] = "test"
	pathParts[2] = "v1"
	pathParts[3] = "q"
	pathParts[4] = "greeting"
	if req.GreetingId == "" {
		return nil, errors.New("required field \"GreetingId\" not set")
	}
	pathParts[5] = req.GreetingId
	path := strings.Join(pathParts, "/")
	if query, err := req.QueryParameters(); err != nil {
		return nil, err
	} else if len(query) > 0 {
		path += "?" + query.Encode()
	}
	resp := &GetGreetingResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s GreetingQueryService) ListGreetings(ctx context.Context, req *ListGreetingsRequest) (*ListGreetingsResponse, error) {
	pathParts := make([]string, 5)
	pathParts[0] = ""
	pathParts[1] = "test"
	pathParts[2] = "v1"
	pathParts[3] = "q"
	pathParts[4] = "greeting"
	path := strings.Join(pathParts, "/")
	if query, err := req.QueryParameters(); err != nil {
		return nil, err
	} else if len(query) > 0 {
		path += "?" + query.Encode()
	}
	resp := &ListGreetingsResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s GreetingQueryService) ListGreetingEvents(ctx context.Context, req *ListGreetingEventsRequest) (*ListGreetingEventsResponse, error) {
	pathParts := make([]string, 7)
	pathParts[0] = ""
	pathParts[1] = "test"
	pathParts[2] = "v1"
	pathParts[3] = "q"
	pathParts[4] = "greeting"
	if req.GreetingId == "" {
		return nil, errors.New("required field \"GreetingId\" not set")
	}
	pathParts[5] = req.GreetingId
	pathParts[6] = "events"
	path := strings.Join(pathParts, "/")
	if query, err := req.QueryParameters(); err != nil {
		return nil, err
	} else if len(query) > 0 {
		path += "?" + query.Encode()
	}
	resp := &ListGreetingEventsResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// GetGreetingRequest
type GetGreetingRequest struct {
	GreetingId string `json:"-" path:"greetingId"`
}

func (s GetGreetingRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	return values, nil
}

// GetGreetingResponse
type GetGreetingResponse struct {
	Greeting *GreetingState `json:"greeting,omitempty"`
}

// ListGreetingsRequest
type ListGreetingsRequest struct {
	Page  *list.PageRequest  `json:"-" query:"page"`
	Query *list.QueryRequest `query:"query" json:"-"`
}

func (s *ListGreetingsRequest) SetPageToken(pageToken string) {
	if s.Page == nil {
		s.Page = &list.PageRequest{}
	}
	s.Page.Token = &pageToken
}

func (s ListGreetingsRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	if s.Page != nil {
		bb, err := json.Marshal(s.Page)
		if err != nil {
			return nil, err
		}
		values.Set("page", string(bb))
	}
	if s.Query != nil {
		bb, err := json.Marshal(s.Query)
		if err != nil {
			return nil, err
		}
		values.Set("query", string(bb))
	}
	return values, nil
}

// ListGreetingsResponse
type ListGreetingsResponse struct {
	Greetings []*GreetingState   `json:"greetings,omitempty"`
	Page      *list.PageResponse `json:"page,omitempty"`
}

func (s ListGreetingsResponse) GetPageToken() *string {
	if s.Page == nil {
		return nil
	}
	return s.Page.NextToken
}

func (s ListGreetingsResponse) GetItems() []*GreetingState {
	return s.Greetings
}

// ListGreetingEventsRequest
type ListGreetingEventsRequest struct {
	GreetingId string             `json:"-" path:"greetingId"`
	Page       *list.PageRequest  `json:"-" query:"page"`
	Query      *list.QueryRequest `json:"-" query:"query"`
}

func (s *ListGreetingEventsRequest) SetPageToken(pageToken string) {
	if s.Page == nil {
		s.Page = &list.PageRequest{}
	}
	s.Page.Token = &pageToken
}

func (s ListGreetingEventsRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	if s.Page != nil {
		bb, err := json.Marshal(s.Page)
		if err != nil {
			return nil, err
		}
		values.Set("page", string(bb))
	}
	if s.Query != nil {
		bb, err := json.Marshal(s.Query)
		if err != nil {
			return nil, err
		}
		values.Set("query", string(bb))
	}
	return values, nil
}

// ListGreetingEventsResponse
type ListGreetingEventsResponse struct {
	Events []*GreetingEvent   `json:"events,omitempty"`
	Page   *list.PageResponse `json:"page,omitempty"`
}

func (s ListGreetingEventsResponse) GetPageToken() *string {
	if s.Page == nil {
		return nil
	}
	return s.Page.NextToken
}

func (s ListGreetingEventsResponse) GetItems() []*GreetingEvent {
	return s.Events
}

// GreetingStatus Proto Enum: test.v1.GreetingStatus
type GreetingStatus string

const (
	GreetingStatus_UNSPECIFIED GreetingStatus = "UNSPECIFIED"
	GreetingStatus_INITIATED   GreetingStatus = "INITIATED"
	GreetingStatus_REPLIED     GreetingStatus = "REPLIED"
)

// GreetingStateData Proto: GreetingStateData
type GreetingStateData struct {
	Name         string  `json:"name,omitempty"`
	ReplyMessage *string `json:"replyMessage,omitempty"`
	AppVersion   string  `json:"appVersion,omitempty"`
}

// GreetingState Proto: GreetingState
type GreetingState struct {
	Metadata   *state.StateMetadata `json:"metadata"`
	GreetingId string               `json:"greetingId,omitempty"`
	Status     string               `json:"status,omitempty"`
	Data       *GreetingStateData   `json:"data,omitempty"`
}

// GreetingEventType_Initiated Proto: GreetingEventType_Initiated
type GreetingEventType_Initiated struct {
	Name        string     `json:"name,omitempty"`
	AppVersion  string     `json:"appVersion,omitempty"`
	WorkerError *TestError `json:"workerError,omitempty"`
}

// TestError Proto: TestError
type TestError struct {
	Message string `json:"message,omitempty"`
	Code    uint32 `json:"code,omitempty"`
}

// GreetingEventType_Replied Proto: GreetingEventType_Replied
type GreetingEventType_Replied struct {
	ReplyMessage string `json:"replyMessage,omitempty"`
}

// GreetingKeys Proto: GreetingKeys
type GreetingKeys struct {
	GreetingId string `json:"greetingId,omitempty"`
}

// GreetingEvent Proto: GreetingEvent
type GreetingEvent struct {
	Metadata   *state.EventMetadata `json:"metadata"`
	GreetingId string               `json:"greetingId,omitempty"`
	Event      *GreetingEventType   `json:"event"`
}

// GreetingEventType Proto Oneof: test.v1.GreetingEventType
type GreetingEventType struct {
	J5TypeKey string                       `json:"!type,omitempty"`
	Initiated *GreetingEventType_Initiated `json:"initiated,omitempty"`
	Replied   *GreetingEventType_Replied   `json:"replied,omitempty"`
}

func (s GreetingEventType) OneofKey() string {
	if s.Initiated != nil {
		return "initiated"
	}
	if s.Replied != nil {
		return "replied"
	}
	return ""
}

func (s GreetingEventType) Type() interface{} {
	if s.Initiated != nil {
		return s.Initiated
	}
	if s.Replied != nil {
		return s.Replied
	}
	return nil
}

// CombinedClient
type CombinedClient struct {
	*GreetingCommandService
	*GreetingQueryService
}

func NewCombinedClient(requester Requester) *CombinedClient {
	return &CombinedClient{
		GreetingCommandService: NewGreetingCommandService(requester),
		GreetingQueryService:   NewGreetingQueryService(requester),
	}
}
