---

run:
  tests: true

linters:
  enable:
    # Defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional
    - exportloopref
    - gofmt
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - typecheck
    - goconst
  disable:
    - wsl
    - prealloc
    - gochecknoglobals
    - unparam
  disable-all: false
  presets:
    - bugs
    - unused
  fast: true

