package dante

// Code generated by jsonapi. DO NOT EDIT.
// Source: github.com/pentops/o5-test-app/internal/genclient/o5/dante/v1/dante

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	messaging "github.com/pentops/o5-test-app/internal/genclient/o5/messaging/v1/messaging"
	list "github.com/pentops/o5-test-app/internal/genclient/psm/list/v1/list"
	state "github.com/pentops/o5-test-app/internal/genclient/psm/state/v1/state"
	url "net/url"
)

type Requester interface {
	Request(ctx context.Context, method string, path string, body interface{}, response interface{}) error
}

// DeadMessageCommandService
type DeadMessageCommandService struct {
	Requester
}

func NewDeadMessageCommandService(requester Requester) *DeadMessageCommandService {
	return &DeadMessageCommandService{
		Requester: requester,
	}
}

func (s DeadMessageCommandService) UpdateDeadMessage(ctx context.Context, req *UpdateDeadMessageRequest) (*UpdateDeadMessageResponse, error) {
	path := fmt.Sprintf("/dante/v1/c/messages/%s/update",
		req.MessageId,
	)
	resp := &UpdateDeadMessageResponse{}
	err := s.Request(ctx, "POST", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s DeadMessageCommandService) ReplayDeadMessage(ctx context.Context, req *ReplayDeadMessageRequest) (*ReplayDeadMessageResponse, error) {
	path := fmt.Sprintf("/dante/v1/c/messages/%s/replay",
		req.MessageId,
	)
	resp := &ReplayDeadMessageResponse{}
	err := s.Request(ctx, "POST", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s DeadMessageCommandService) RejectDeadMessage(ctx context.Context, req *RejectDeadMessageRequest) (*RejectDeadMessageResponse, error) {
	path := fmt.Sprintf("/dante/v1/c/messages/%s/shelve",
		req.MessageId,
	)
	resp := &RejectDeadMessageResponse{}
	err := s.Request(ctx, "POST", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// DeadMessageQueryService
type DeadMessageQueryService struct {
	Requester
}

func NewDeadMessageQueryService(requester Requester) *DeadMessageQueryService {
	return &DeadMessageQueryService{
		Requester: requester,
	}
}

func (s DeadMessageQueryService) GetDeadMessage(ctx context.Context, req *GetDeadMessageRequest) (*GetDeadMessageResponse, error) {
	path := fmt.Sprintf("/dante/v1/q/message/%s",
		req.MessageId,
	)
	resp := &GetDeadMessageResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s DeadMessageQueryService) ListDeadMessages(ctx context.Context, req *ListDeadMessagesRequest) (*ListDeadMessagesResponse, error) {
	path := fmt.Sprintf("/dante/v1/q/messages")
	resp := &ListDeadMessagesResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s DeadMessageQueryService) ListDeadMessageEvents(ctx context.Context, req *ListDeadMessageEventsRequest) (*ListDeadMessageEventsResponse, error) {
	path := fmt.Sprintf("/dante/v1/q/message/%s/events",
		req.MessageId,
	)
	resp := &ListDeadMessageEventsResponse{}
	err := s.Request(ctx, "GET", path, req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// DeadMessageKeys Proto: o5.dante.v1.DeadMessageKeys
type DeadMessageKeys struct {
	MessageId string `json:"messageId,omitempty"`
}

// DeadMessageData Proto: o5.dante.v1.DeadMessageData
type DeadMessageData struct {
	Notification   *messaging.DeadMessage `json:"notification,omitempty"`
	CurrentVersion *DeadMessageVersion    `json:"currentVersion,omitempty"`
}

// DeadMessageEvent Proto: o5.dante.v1.DeadMessageEvent
type DeadMessageEvent struct {
	Metadata *state.EventMetadata  `json:"metadata"`
	Keys     *DeadMessageKeys      `json:"keys"`
	Event    *DeadMessageEventType `json:"event"`
}

// DeadMessageState Proto: o5.dante.v1.DeadMessageState
type DeadMessageState struct {
	Metadata *state.StateMetadata `json:"metadata"`
	Keys     *DeadMessageKeys     `json:"keys"`
	Status   string               `json:"status,omitempty"`
	Data     *DeadMessageData     `json:"data,omitempty"`
}

// RejectDeadMessageResponse
type RejectDeadMessageResponse struct {
	Message *DeadMessageState `json:"message"`
}

// GetDeadMessageResponse
type GetDeadMessageResponse struct {
	Message *DeadMessageState   `json:"message"`
	Events  []*DeadMessageEvent `json:"events,omitempty"`
}

// DeadMessageEventType_Updated Proto: o5.dante.v1.DeadMessageEventType.Updated
type DeadMessageEventType_Updated struct {
	Spec *DeadMessageVersion `json:"spec,omitempty"`
}

// DeadMessageEventType_Rejected Proto: o5.dante.v1.DeadMessageEventType.Rejected
type DeadMessageEventType_Rejected struct {
	Reason string `json:"reason,omitempty"`
}

// ListDeadMessageEventsRequest
type ListDeadMessageEventsRequest struct {
	MessageId string             `json:"-" path:"messageId"`
	Page      *list.PageRequest  `json:"-" query:"page"`
	Query     *list.QueryRequest `json:"-" query:"query"`
}

func (s ListDeadMessageEventsRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	if s.Page != nil {
		bb, err := json.Marshal(s.Page)
		if err != nil {
			return nil, err
		}
		values.Set("page", string(bb))
	}
	if s.Query != nil {
		bb, err := json.Marshal(s.Query)
		if err != nil {
			return nil, err
		}
		values.Set("query", string(bb))
	}
	return values, nil
}

func (s *ListDeadMessageEventsRequest) SetPageToken(pageToken string) {
	if s.Page == nil {
		s.Page = &list.PageRequest{}
	}
	s.Page.Token = &pageToken
}

// DeadMessageEventType_Replayed Proto: o5.dante.v1.DeadMessageEventType.Replayed
type DeadMessageEventType_Replayed struct {
}

// ListDeadMessageEventsResponse
type ListDeadMessageEventsResponse struct {
	Events []*DeadMessageEvent `json:"events,omitempty"`
	Page   *list.PageResponse  `json:"page,omitempty"`
}

func (s ListDeadMessageEventsResponse) GetPageToken() *string {
	if s.Page == nil {
		return nil
	}
	return s.Page.NextToken
}

func (s ListDeadMessageEventsResponse) GetItems() []*DeadMessageEvent {
	return s.Events
}

// UpdateDeadMessageRequest
type UpdateDeadMessageRequest struct {
	MessageId         string              `json:"-" path:"messageId"`
	ReplacesVersionId string              `json:"replacesVersionId,omitempty"`
	VersionId         *string             `json:"versionId,omitempty"`
	Message           *DeadMessageVersion `json:"message"`
}

// DeadMessageVersion_SQSMessage Proto: o5.dante.v1.DeadMessageVersion.SQSMessage
type DeadMessageVersion_SQSMessage struct {
	QueueUrl   string            `json:"queueUrl,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
}

// ReplayDeadMessageResponse
type ReplayDeadMessageResponse struct {
	Message *DeadMessageState `json:"message"`
}

// RejectDeadMessageRequest
type RejectDeadMessageRequest struct {
	MessageId string `path:"messageId" json:"-"`
	Reason    string `json:"reason,omitempty"`
}

// GetDeadMessageRequest
type GetDeadMessageRequest struct {
	MessageId string `json:"-" path:"messageId"`
}

// DeadMessageEventType_Notified Proto: o5.dante.v1.DeadMessageEventType.Notified
type DeadMessageEventType_Notified struct {
	Notification *messaging.DeadMessage `json:"notification,omitempty"`
}

// ListDeadMessagesResponse
type ListDeadMessagesResponse struct {
	Messages []*DeadMessageState `json:"messages,omitempty"`
	Page     *list.PageResponse  `json:"page,omitempty"`
}

func (s ListDeadMessagesResponse) GetPageToken() *string {
	if s.Page == nil {
		return nil
	}
	return s.Page.NextToken
}

func (s ListDeadMessagesResponse) GetItems() []*DeadMessageState {
	return s.Messages
}

// DeadMessageVersion Proto: o5.dante.v1.DeadMessageVersion
type DeadMessageVersion struct {
	VersionId  string                         `json:"versionId,omitempty"`
	Message    *messaging.Message             `json:"message,omitempty"`
	SqsMessage *DeadMessageVersion_SQSMessage `json:"sqsMessage,omitempty"`
}

// UpdateDeadMessageResponse
type UpdateDeadMessageResponse struct {
	Message *DeadMessageState `json:"message"`
}

// ReplayDeadMessageRequest
type ReplayDeadMessageRequest struct {
	MessageId string `json:"-" path:"messageId"`
}

// DeadMessageEventType Proto: o5.dante.v1.DeadMessageEventType
type DeadMessageEventType struct {
	Type *DeadMessageEventType_type `json:"type,omitempty"`
}

// DeadMessageEventType_type Proto: o5.dante.v1.DeadMessageEventType.type
type DeadMessageEventType_type struct {
	Notified *DeadMessageEventType_Notified `json:"notified,omitempty"`
	Updated  *DeadMessageEventType_Updated  `json:"updated,omitempty"`
	Replayed *DeadMessageEventType_Replayed `json:"replayed,omitempty"`
	Rejected *DeadMessageEventType_Rejected `json:"rejected,omitempty"`
}

func (s DeadMessageEventType_type) OneofKey() string {
	if s.Notified != nil {
		return "notified"
	}
	if s.Updated != nil {
		return "updated"
	}
	if s.Replayed != nil {
		return "replayed"
	}
	if s.Rejected != nil {
		return "rejected"
	}
	return ""
}

func (s DeadMessageEventType_type) Type() interface{} {
	if s.Notified != nil {
		return s.Notified
	}
	if s.Updated != nil {
		return s.Updated
	}
	if s.Replayed != nil {
		return s.Replayed
	}
	if s.Rejected != nil {
		return s.Rejected
	}
	return nil
}

// ListDeadMessagesRequest
type ListDeadMessagesRequest struct {
	Page  *list.PageRequest  `json:"-" query:"page"`
	Query *list.QueryRequest `query:"query" json:"-"`
}

func (s ListDeadMessagesRequest) QueryParameters() (url.Values, error) {
	values := url.Values{}
	if s.Page != nil {
		bb, err := json.Marshal(s.Page)
		if err != nil {
			return nil, err
		}
		values.Set("page", string(bb))
	}
	if s.Query != nil {
		bb, err := json.Marshal(s.Query)
		if err != nil {
			return nil, err
		}
		values.Set("query", string(bb))
	}
	return values, nil
}

func (s *ListDeadMessagesRequest) SetPageToken(pageToken string) {
	if s.Page == nil {
		s.Page = &list.PageRequest{}
	}
	s.Page.Token = &pageToken
}
